### ISSUE TITLE
V2 milestone

### ISSUE THREAD

**Issue by soranoba** [soranoba/henge#3]
- [ ] Delete `ValueConverter.Float[r]Ptr`
  - [x] Replace to `ValueConverter.FloatPtr` (v1.2.0)
- [ ] Change options type of New method (`func(*ConverterOpts)`)
  - Change struct ConverterOpts to private
